name: Deploy to unfoundbox.com

on:
  push:
    branches: [ "main" ]

env:
  HUGO_VERSION: 0.121.2

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # For Hugo themes

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: false

      - name: Build with Hugo
        run: |
          hugo --minify --gc --cleanDestinationDir
          echo "unfoundbox.com" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false  # Remove old files on deploy 